server:
  port: 9091
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: java14user
    password: root
  data:
    mongodb:
      host: localhost
      port: 27027
      database: HamburgerShopDB
      username: bilge
      password: bilge!123
authservice:
  secret:
    secret-key: ${JAVA14_SECRET_KEY}
    issuer: ${JAVA14_ISSUER}

