server:
  port: 9090
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  data:
    mongodb:
      host: localhost
      port: 27017
      database: HamburgerShopDB
      username: bilge
      password: bilge!123

authservice:
  secret:
    secret-key: ${JAVA14_SECRET_KEY}
    issuer: ${JAVA14_ISSUER}

